# Generated by Django 5.1.15 on 2026-10-03 10:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("agreements", "0002_agreement_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="agreement",
            name="additional_terms",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="cancellation_terms",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="content",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="agreement",
            name="delivery_terms",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="party_one_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="agreement",
            name="party_one_name",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name="agreement",
            name="party_two_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="agreement",
            name="payment_amount",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="agreement",
            name="payment_terms",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="rejected_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="responsibilities",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="scope_of_work",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="share_token",
            field=models.CharField(
                blank=True, editable=False, max_length=64, null=True, unique=True
            ),
        ),
        migrations.AddField(
            model_name="agreement",
            name="signed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="agreement",
            name="viewed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="AgreementHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_type", models.CharField(max_length=50)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="agreements.agreement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "agreement history",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="Signature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("party_one", "Party 1 (owner)"),
                            ("party_two", "Party 2 (counterparty)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("signed_name", models.CharField(max_length=200)),
                ("signer_email", models.EmailField(max_length=254)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("signed_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "agreement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="signatures",
                        to="agreements.agreement",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["signed_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("agreement", "role"), name="one_signature_per_role"
                    )
                ],
            },
        ),
    ]
